-- MySQL Script generated by MySQL Workbench
-- Mon Aug  4 17:43:47 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema school
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema school
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `school` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `school` ;

-- -----------------------------------------------------
-- Table `school`.`teachers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `school`.`teachers` (
  `TeacherID` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(100) NULL DEFAULT NULL,
  `SubjectSpecialization` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`TeacherID`))
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `school`.`classes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `school`.`classes` (
  `ClassID` INT NOT NULL AUTO_INCREMENT,
  `ClassName` VARCHAR(100) NULL DEFAULT NULL,
  `TeacherID` INT NULL DEFAULT NULL,
  PRIMARY KEY (`ClassID`),
  INDEX `TeacherID` (`TeacherID` ASC) VISIBLE,
  CONSTRAINT `classes_ibfk_1`
    FOREIGN KEY (`TeacherID`)
    REFERENCES `school`.`teachers` (`TeacherID`))
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `school`.`students`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `school`.`students` (
  `StudentID` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(100) NULL DEFAULT NULL,
  `DateOfBirth` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`StudentID`))
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `school`.`enrollments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `school`.`enrollments` (
  `EnrollmentID` INT NOT NULL AUTO_INCREMENT,
  `StudentID` INT NULL DEFAULT NULL,
  `ClassID` INT NULL DEFAULT NULL,
  `EnrollmentDate` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`EnrollmentID`),
  INDEX `StudentID` (`StudentID` ASC) VISIBLE,
  INDEX `ClassID` (`ClassID` ASC) VISIBLE,
  CONSTRAINT `enrollments_ibfk_1`
    FOREIGN KEY (`StudentID`)
    REFERENCES `school`.`students` (`StudentID`)
    ON DELETE CASCADE,
  CONSTRAINT `enrollments_ibfk_2`
    FOREIGN KEY (`ClassID`)
    REFERENCES `school`.`classes` (`ClassID`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
